# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Hamster

on:
  push:
    branches: [ "fix/gh-actions" ]

jobs:
  build:

    # run on self-hosted runner and macos-latest for arm64 architecture and intel architecture
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ self-hosted, macos ]

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.11"

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2app
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    - name: Generate app for intel architecture
      run: |
          python setup.py py2app
          mv dist dist-intel
      if: runner.os == 'macos'

    - name: Generate app for arm64 architecture
      run: |
        python setup.py py2app
        mv dist dist-arm64
      if: runner.os == 'self-hosted'

    - name: Convert dist-intel to DMG
      run: |
        hdiutil create -volname "Hamster" -srcfolder dist-intel -ov -format UDZO dist-intel/Hamster-intel.dmg
      if: runner.os == 'macos'

    - name: Convert dist-arm64 to DMG
      run: |
        hdiutil create -volname "Hamster" -srcfolder dist-arm64 -ov -format UDZO dist-arm64/Hamster-darwin.dmg
      if: runner.os == 'self-hosted'

    - name: Upload intel app
      uses: actions/upload-artifact@v2
      with:
        name: Hamster
        path: dist-intel/Hamster-intel.dmg
      if: runner.os == 'macos'

    - name: Upload arm64 app
      uses: actions/upload-artifact@v2
      with:
        name: Hamster
        path: dist-arm64/Hamster-darwin.dmg
      if: runner.os == 'self-hosted'


