# This workflow will install Python dependencies, run tests and lint with a single version of Python
# For more information see: https://docs.github.com/en/actions/automating-builds-and-tests/building-and-testing-python

name: Hamster

on:
  push:
    branches: [ "fix/gh-actions" ]

jobs:
  build:

    runs-on: self-hosted

    steps:
    - uses: actions/checkout@v3
    
    - name: Set up Python 3.10.11
      uses: actions/setup-python@v3
      with:
        python-version: "3.10.11"

    - name: List current directory
      run: |
        ls -la
        uname -a

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install py2app
        if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

    # - name: Generate app for x86_64 architecture
    #   run: |
    #     arch -x86_64 python setup.py py2app --arch x86_64
    #     mv dist dist-x86_64

    - name: Generate app for arm64 architecture
      run: |
        python setup.py py2app
        mv dist dist-arm64

    # - name: Upload x86_64 app
    #   uses: actions/upload-artifact@v2
    #   with:
    #     name: dist-x86_64
    #     path: dist-x86_64

    - name: List current directory
      run: |
        ls -la
        uname -a
        ls -la dist-arm64
    
    - name: Change mode of dist-arm64
      run: |
        chmod +x dist-arm64/Hamster.app/Contents/MacOS/Hamster
        chmod +x dist-arm64/Hamster.app/Contents/MacOS/python
        ls -la dist-arm64/Hamster.app/Contents/MacOS/

    - name: Create tar file
      run: |
        tar -czvf dist-arm64.tar.gz dist-arm64
        ls -la

    - name: Upload arm64 app
      uses: actions/upload-artifact@v2
      with:
        name: dist-arm64.tar.gz
        path: dist-arm64
        preserve-permissions: true
